import {
  IconAlertCircle,
  IconAlertCircleOutline,
  IconAlertTriangle,
  IconAlertTriangleOutline,
  IconArchive,
  IconArchiveOutline,
  IconArrowCircleDown,
  IconArrowCircleDownOutline,
  IconArrowCircleLeft,
  IconArrowCircleLeftOutline,
  IconArrowCircleRight,
  IconArrowCircleRightOutline,
  IconArrowCircleUp,
  IconArrowCircleUpOutline,
  IconArrowDownLeftOutline,
  IconArrowDownOutline,
  IconArrowDownRightOutline,
  IconArrowDownTurnLeftOutline,
  IconArrowDownTurnRightOutline,
  IconArrowLeftOutline,
  IconArrowLeftTurnDownOutline,
  IconArrowLeftTurnUpOutline,
  IconArrowMoveOutline,
  IconArrowRightOutline,
  IconArrowRightTurnDownOutline,
  IconArrowRightTurnUpOutline,
  IconArrowUpLeftOutline,
  IconArrowUpOutline,
  IconArrowUpRightOutline,
  IconArrowUpTurnLeftOutline,
  IconArrowUpTurnRightOutline,
  IconAtOutline,
  IconAward,
  IconAwardOutline,
  IconBackspace,
  IconBackspaceOutline,
  IconBackward,
  IconBackwardOutline,
  IconBackwardStep,
  IconBackwardStepOutline,
  IconBarChartOutline,
  IconBattery,
  IconBatteryBolt,
  IconBatteryBoltOutline,
  IconBatteryEmptyOutline,
  IconBehance,
  IconBehanceOutline,
  IconBell,
  IconBellOutline,
  IconBellSlash,
  IconBellSlashOutline,
  IconBluetoothOutline,
  IconBolt,
  IconBoltOutline,
  IconBoltSlash,
  IconBoltSlashOutline,
  IconBook,
  IconBookOpen,
  IconBookOpenOutline,
  IconBookOutline,
  IconBookmark,
  IconBookmarkOutline,
  IconBriefcase,
  IconBriefcaseOutline,
  IconBroadcast,
  IconBroadcastOutline,
  IconBulb,
  IconBulbOutline,
  IconCalendar,
  IconCalendarOutline,
  IconCamera,
  IconCameraOutline,
  IconCarretDown,
  IconCarretDownOutline,
  IconCarretLeft,
  IconCarretLeftOutline,
  IconCarretRight,
  IconCarretRightOutline,
  IconCarretUp,
  IconCarretUpOutline,
  IconCastOutline,
  IconCheckCircle2,
  IconCheckCircle2Outline,
  IconCheckCircleOutline,
  IconCheckDoubleOutline,
  IconCheckOutline,
  IconCheckSquare,
  IconCheckSquare2Outline,
  IconCheckSquareOutline,
  IconChevronDownOutline,
  IconChevronLeftOutline,
  IconChevronRightOutline,
  IconChevronUpOutline,
  IconChevronsDownOutline,
  IconChevronsLeftOutline,
  IconChevronsRightOutline,
  IconChevronsUpOutline,
  IconCircleDot,
  IconCircleDotOutline,
  IconCircleOutline,
  IconCircleSlashOutline,
  IconCircleXmark,
  IconCircleXmarkOutline,
  IconClipboard,
  IconClipboardOutline,
  IconClockThree,
  IconClockThreeOutline,
  IconCloudDownload,
  IconCloudDownloadOutline,
  IconCloudUpload,
  IconCloudUploadOutline,
  IconCodeDownloadOutline,
  IconCodeOutline,
  IconCollapseOutline,
  IconCompass,
  IconCompassOutline,
  IconCopy,
  IconCopyOutline,
  IconCreditCard,
  IconCreditCard2Outline,
  IconCreditCardOutline,
  IconCropOutline,
  IconCube,
  IconCubeOutline,
  IconDekstopOutline,
  IconDownloadOutline,
  IconDroplet,
  IconDropletOutline,
  IconDropletSlash,
  IconDropletSlashOutline,
  IconEdit,
  IconEdit2,
  IconEdit2Outline,
  IconEdit3Outline,
  IconEditOutline,
  IconElipsisOutline,
  IconElipsisVerticalOutline,
  IconEnvelop,
  IconEnvelopOutline,
  IconExpandOutline,
  IconExternalLinkOutline,
  IconEye,
  IconEyeOffOutline,
  IconEyeOutline,
  IconEyeSlash,
  IconEyeSlashOutline,
  IconFacebook,
  IconFacebookOutline,
  IconFile,
  IconFileLines,
  IconFileLinesOutline,
  IconFileMinOutline,
  IconFileOutline,
  IconFilePlus,
  IconFilePlusOutline,
  IconFilter,
  IconFilterOutline,
  IconFire,
  IconFireOutline,
  IconFlag,
  IconFlipOutline,
  IconFolder,
  IconFolderMin,
  IconFolderMinOutline,
  IconFolderOutline,
  IconFolderPlus,
  IconFolderPlusOutline,
  IconForward,
  IconForwardOutline,
  IconForwardStep,
  IconForwardStepOutline,
  IconGift,
  IconGiftOutline,
  IconGithub,
  IconGithubOutline,
  IconGlobe2,
  IconGlobe2Outline,
  IconGlobe3,
  IconGlobeOutline,
  IconGoogle,
  IconGoogleOutline,
  IconGrid,
  IconGridOutline,
  IconGridRound,
  IconGridRoundOutline,
  IconHardDrive,
  IconHardDriveOutline,
  IconHashOutline,
  IconHeadphone,
  IconHeadphoneOutline,
  IconHeightScaleOutline,
  IconHome,
  IconHomeOutline,
  IconImage,
  IconImage2,
  IconImageOutline,
  IconInbox,
  IconInboxOutline,
  IconInfo,
  IconInfoOutline,
  IconLayerGroup,
  IconLayerGroupOutline,
  IconLayout,
  IconLayoutOutline,
  IconLink2Outline,
  IconLinkOutline,
  IconLinkedin,
  IconLinkedinOutline,
  IconListOutline,
  IconLoaderOutline,
  IconLock,
  IconLockOutline,
  IconLove,
  IconLoveOutline,
  IconMagnifyingGlassMin,
  IconMagnifyingGlassMinOutline,
  IconMagnifyingGlassOutline,
  IconMagnifyingGlassPlus,
  IconMagnifyingGlassPlusOutline,
  IconMaps,
  IconMapsOutline,
  IconMenu2Outline,
  IconMenu3Outline,
  IconMenuOutline,
  IconMergeOutline,
  IconMessageCircle,
  IconMessageCircleOutline,
  IconMessageSquare,
  IconMessageSquareOutline,
  IconMic,
  IconMicOff,
  IconMicOffOutline,
  IconMicOutline,
  IconMinCircle,
  IconMinCircleOutline,
  IconMinOutline,
  IconMinSquare,
  IconMinSquareOutline,
  IconMonitor,
  IconMoon,
  IconMoonOutline,
  IconMovie,
  IconMovieOutline,
  IconMusic,
  IconMusicOutline,
  IconNavigation,
  IconNavigationOutline,
  IconNavigationUp,
  IconNavigationUpOutline,
  IconNpm,
  IconNpmOutline,
  IconPaintBrush,
  IconPaintBrushOutline,
  IconPalette,
  IconPaletteOutline,
  IconPantone,
  IconPantoneOutline,
  IconPaperPlaneOutline,
  IconPaperclipOutline,
  IconPaperclipUpOutline,
  IconPauseCircle,
  IconPauseCircleOutline,
  IconPencil,
  IconPencilOutline,
  IconPercentOutline,
  IconPerson,
  IconPersonCheck,
  IconPersonCheckOutline,
  IconPersonMin,
  IconPersonMinOutline,
  IconPersonOutline,
  IconPersonPlus,
  IconPersonPlusOutline,
  IconPersonX,
  IconPersonXOutline,
  IconPersons,
  IconPersonsOutline,
  IconPhone,
  IconPhoneCall,
  IconPhoneCallOutline,
  IconPhoneMissed,
  IconPhoneMissedOutline,
  IconPhoneOff,
  IconPhoneOffOutline,
  IconPhoneOutline,
  IconPieChart,
  IconPieChart2,
  IconPieChartOutline,
  IconPinLocation,
  IconPinLocationOutline,
  IconPlayCircle,
  IconPlayCircleOutline,
  IconPlusCircle,
  IconPlusCircleOutline,
  IconPlusOutline,
  IconPlusSquare,
  IconPlusSquareOutline,
  IconPowerOffOutline,
  IconPriceTag,
  IconPriceTagOutline,
  IconPrinter,
  IconPrinterOutline,
  IconPulseOutline,
  IconQuestionCircle,
  IconQuestionCircleOutline,
  IconQuestionOutline,
  IconRecording,
  IconRecordingOutline,
  IconRepeatOutline,
  IconReply,
  IconReplyOutline,
  IconRightLeftOutline,
  IconRotateOutline,
  IconRotateRightOutline,
  IconSave,
  IconSaveOutline,
  IconScissorsOutline,
  IconSetting,
  IconSetting2,
  IconSetting2Outline,
  IconSettingOutline,
  IconShakeOutline,
  IconShareNode,
  IconShareNodeOutline,
  IconShield,
  IconShieldOutline,
  IconShieldSlash,
  IconShieldSlashOutline,
  IconShoppingBag,
  IconShoppingBagOutline,
  IconShoppingCart,
  IconShoppingCartOutline,
  IconShuffle2Outline,
  IconShuffleOutline,
  IconSignOutOutline,
  IconSignalOutline,
  IconSigninOutline,
  IconSliders,
  IconSlidersOutline,
  IconSlidersUp,
  IconSlidersUpOutline,
  IconSmartphone,
  IconSmartphoneOutline,
  IconSpeaker,
  IconSpeakerOutline,
  IconSquareCircle,
  IconSquareCircleOutline,
  IconSquareOutline,
  IconStar,
  IconStarOutline,
  IconStopwatch,
  IconStopwatchOutline,
  IconSun,
  IconSunOutline,
  IconTV,
  IconTVOutline,
  IconTextOutline,
  IconThermometer,
  IconThermometerMin,
  IconThermometerMinOutline,
  IconThermometerOutline,
  IconThermometerPlus,
  IconThermometerPlusOutline,
  IconToogleOff,
  IconToogleOffOutline,
  IconToogleOn,
  IconToogleOnOutline,
  IconTrash,
  IconTrash2,
  IconTrash2Outline,
  IconTrashOutline,
  IconTrendingDownOutline,
  IconTrendingUpOutline,
  IconTruck,
  IconTruckOutline,
  IconTwitter,
  IconTwitterOutline,
  IconUmbrela,
  IconUmbrelaOutline,
  IconUnlock,
  IconUnlockOutline,
  IconUploadOutline,
  IconVideo,
  IconVideoOff,
  IconVideoOffOutline,
  IconVideoOutline,
  IconVolumeHigh,
  IconVolumeHighOutline,
  IconVolumeLow,
  IconVolumeLowOutline,
  IconVolumeOff,
  IconVolumeOffOutline,
  IconVolumeSlash,
  IconVolumeSlashOutline,
  IconWeightScale,
  IconWeightScaleOutline,
  IconWifiOutline,
  IconWifiSlashOutline,
  IconWindow,
  IconWindowDockOutline,
  IconWindowOutline,
  IconXmarkOutline,
  IconXmarkSquare,
  IconXmarkSquareOutline,
} from "@envio-ui/icons";
import React from "react";

interface IconMap {
  name: string;
  children: React.ReactNode;
}

type IconMapObject = Record<string, IconMap[]>;

// alert
const alert: IconMapObject = {
  outline: [
    { name: "IconAlertCircleOutline", children: <IconAlertCircleOutline /> },
    {
      name: "IconAlertTriangleOutline",
      children: <IconAlertTriangleOutline />,
    },
    { name: "IconInfoOutline", children: <IconInfoOutline /> },
    { name: "IconQuestionOutline", children: <IconQuestionOutline /> },
    {
      name: "IconQuestionCircleOutline",
      children: <IconQuestionCircleOutline />,
    },
    { name: "IconBellOutline", children: <IconBellOutline /> },
    { name: "IconBellSlashOutline", children: <IconBellSlashOutline /> },
    { name: "IconStopwatchOutline", children: <IconStopwatchOutline /> },
  ],
  fill: [
    {
      name: "IconAlertCircle",
      children: <IconAlertCircle />,
    },
    { name: "IconAlertTriangle", children: <IconAlertTriangle /> },
    { name: "IconBell", children: <IconBell /> },
    { name: "IconBellSlash", children: <IconBellSlash /> },
    { name: "IconInfo", children: <IconInfo /> },
    { name: "IconQuestionCircle", children: <IconQuestionCircle /> },
    { name: "IconStopwatch", children: <IconStopwatch /> },
  ],
};
// arrow
const arrow: IconMapObject = {
  outline: [
    {
      name: "IconArrowCircleDownOutline",
      children: <IconArrowCircleDownOutline />,
    },
    {
      name: "IconArrowCircleUpOutline",
      children: <IconArrowCircleUpOutline />,
    },
    {
      name: "IconArrowCircleLeftOutline",
      children: <IconArrowCircleLeftOutline />,
    },
    {
      name: "IconArrowCircleRightOutline",
      children: <IconArrowCircleRightOutline />,
    },
    { name: "IconArrowDownOutline", children: <IconArrowDownOutline /> },
    { name: "IconArrowUpOutline", children: <IconArrowUpOutline /> },
    { name: "IconArrowLeftOutline", children: <IconArrowLeftOutline /> },
    { name: "IconArrowRightOutline", children: <IconArrowRightOutline /> },
    { name: "IconArrowUpRightOutline", children: <IconArrowUpRightOutline /> },
    { name: "IconsArrowUpLeftOutline", children: <IconArrowUpLeftOutline /> },
    {
      name: "IconArrowDownLeftOutline",
      children: <IconArrowDownLeftOutline />,
    },
    {
      name: "IconArrowDownRightOutline",
      children: <IconArrowDownRightOutline />,
    },
    { name: "IconArrowMoveOutline", children: <IconArrowMoveOutline /> },
    { name: "IconChevronDownOutline", children: <IconChevronDownOutline /> },
    { name: "IconChevronLeftOutline", children: <IconChevronLeftOutline /> },
    { name: "IconChevronRightOutline", children: <IconChevronRightOutline /> },
    { name: "IconChevronUpOutline", children: <IconChevronUpOutline /> },
    { name: "IconChevronsDownOutline", children: <IconChevronsDownOutline /> },
    { name: "IconChevronsLeftOutline", children: <IconChevronsLeftOutline /> },
    {
      name: "IconChevronsRightOutline",
      children: <IconChevronsRightOutline />,
    },
    { name: "IconChevronsUpOutline", children: <IconChevronsUpOutline /> },
    { name: "IconShuffleOutline", children: <IconShuffleOutline /> },
    { name: "IconShuffle2Outline", children: <IconShuffle2Outline /> },
    {
      name: "IconArrowDownTurnLeftOutline",
      children: <IconArrowDownTurnLeftOutline />,
    },
    {
      name: "IconArrowDownTurnRightOutline",
      children: <IconArrowDownTurnRightOutline />,
    },
    {
      name: "IconArrowLeftTurnDownOutline",
      children: <IconArrowLeftTurnDownOutline />,
    },
    {
      name: "IconArrowLeftTurnUpOutline",
      children: <IconArrowLeftTurnUpOutline />,
    },
    {
      name: "IconArrowRightTurnDownOutline",
      children: <IconArrowRightTurnDownOutline />,
    },
    {
      name: "IconArrowRightTurnUpOutline",
      children: <IconArrowRightTurnUpOutline />,
    },
    {
      name: "IconArrowUpTurnLeftOutline",
      children: <IconArrowUpTurnLeftOutline />,
    },
    {
      name: "IconArrowUpTurnRightOutline",
      children: <IconArrowUpTurnRightOutline />,
    },
    { name: "IconCarretDownOutline", children: <IconCarretDownOutline /> },
    { name: "IconCarretLeftOutline", children: <IconCarretLeftOutline /> },
    { name: "IconCarretRightOutline", children: <IconCarretRightOutline /> },
    { name: "IconCarretUpOutline", children: <IconCarretUpOutline /> },
    { name: "IconCollapseOutline", children: <IconCollapseOutline /> },
    { name: "IconExpandOutline", children: <IconExpandOutline /> },
    { name: "IconRepeatOutline", children: <IconRepeatOutline /> },
    { name: "IconRightLeftOutline", children: <IconRightLeftOutline /> },
    { name: "IconRotateOutline", children: <IconRotateOutline /> },
    { name: "IconRotateRightOutline", children: <IconRotateRightOutline /> },
  ],
  fill: [
    {
      name: "IconArrowCircleDown",
      children: <IconArrowCircleDown />,
    },
    {
      name: "IconArrowCircleUp",
      children: <IconArrowCircleUp />,
    },
    {
      name: "IconArrowCircleLeft",
      children: <IconArrowCircleLeft />,
    },
    {
      name: "IconArrowCircleRight",
      children: <IconArrowCircleRight />,
    },
    { name: "IconCarretDown", children: <IconCarretDown /> },
    { name: "IconCarretLeft", children: <IconCarretLeft /> },
    { name: "IconCarretRight", children: <IconCarretRight /> },
    { name: "IconCarretUp", children: <IconCarretUp /> },
  ],
};
// bussiness
const bussiness: IconMapObject = {
  outline: [
    { name: "IconBarChartOutline", children: <IconBarChartOutline /> },
    { name: "IconTrendingDownOutline", children: <IconTrendingDownOutline /> },
    { name: "IconTrendingUpOutline", children: <IconTrendingUpOutline /> },
    { name: "IconCreditCard2Outline", children: <IconCreditCard2Outline /> },
    { name: "IconPieChartOutline", children: <IconPieChartOutline /> },
    { name: "IconBriefcaseOutline", children: <IconBriefcaseOutline /> },
    { name: "IconPriceTagOutline", children: <IconPriceTagOutline /> },
    { name: "IconShoppingBagOutline", children: <IconShoppingBagOutline /> },
    { name: "IconShoppingCartOutline", children: <IconShoppingCartOutline /> },
    { name: "IconCreditCardOutline", children: <IconCreditCardOutline /> },
    { name: "IconGlobeOutline", children: <IconGlobeOutline /> },
    { name: "IconGlobe2Outline", children: <IconGlobe2Outline /> },
    { name: "IconPaperclipOutline", children: <IconPaperclipOutline /> },
    { name: "IconPaperclipUpOutline", children: <IconPaperclipUpOutline /> },
  ],
  fill: [
    { name: "IconBriefcase", children: <IconBriefcase /> },
    { name: "IconCreditCard", children: <IconCreditCard /> },
    { name: "IconGlobe2", children: <IconGlobe2 /> },
    { name: "IconGlobe3", children: <IconGlobe3 /> },
    { name: "IconPieChart", children: <IconPieChart /> },
    { name: "IconPieChart2", children: <IconPieChart2 /> },
    { name: "IconPriceTag", children: <IconPriceTag /> },
    { name: "IconShoppingBag", children: <IconShoppingBag /> },
    { name: "IconShoppingCart", children: <IconShoppingCart /> },
  ],
};
// coding
const coding: IconMapObject = {
  outline: [
    { name: "IconBookmarkOutline", children: <IconBookmarkOutline /> },
    { name: "IconCopyOutline", children: <IconCopyOutline /> },
    { name: "IconExternalLinkOutline", children: <IconExternalLinkOutline /> },
    { name: "IconFilterOutline", children: <IconFilterOutline /> },
    { name: "IconSettingOutline", children: <IconSettingOutline /> },
    { name: "IconSetting2Outline", children: <IconSetting2Outline /> },
    { name: "IconSignOutOutline", children: <IconSignOutOutline /> },
    { name: "IconSigninOutline", children: <IconSigninOutline /> },
    { name: "IconUploadOutline", children: <IconUploadOutline /> },
    { name: "IconDownloadOutline", children: <IconDownloadOutline /> },
    {
      name: "IconCloudDownloadOutline",
      children: <IconCloudDownloadOutline />,
    },
    { name: "IconCloudUploadOutline", children: <IconCloudUploadOutline /> },
    { name: "IconHashOutline", children: <IconHashOutline /> },
    { name: "IconSaveOutline", children: <IconSaveOutline /> },
    { name: "IconCastOutline", children: <IconCastOutline /> },
    { name: "IconCodeOutline", children: <IconCodeOutline /> },
    { name: "IconCodeDownloadOutline", children: <IconCodeDownloadOutline /> },
    { name: "IconCubeOutline", children: <IconCubeOutline /> },
    { name: "IconMergeOutline", children: <IconMergeOutline /> },
    { name: "IconWindowOutline", children: <IconWindowOutline /> },
    { name: "IconWindowDockOutline", children: <IconWindowDockOutline /> },
  ],
  fill: [
    { name: "IconBookmark", children: <IconBookmark /> },
    { name: "IconCloudDownload", children: <IconCloudDownload /> },
    { name: "IconCloudUpload", children: <IconCloudUpload /> },
    { name: "IconCopy", children: <IconCopy /> },
    { name: "IconCube", children: <IconCube /> },
    { name: "IconFilter", children: <IconFilter /> },
    { name: "IconSave", children: <IconSave /> },
    { name: "IconSetting", children: <IconSetting /> },
    { name: "IconSetting2", children: <IconSetting2 /> },
    { name: "IconWindow", children: <IconWindow /> },
  ],
};
// communication
const communication: IconMapObject = {
  outline: [
    { name: "IconBluetoothOutline", children: <IconBluetoothOutline /> },
    {
      name: "IconMessageCircleOutline",
      children: <IconMessageCircleOutline />,
    },
    {
      name: "IconMessageSquareOutline",
      children: <IconMessageSquareOutline />,
    },
    { name: "IconMicOutline", children: <IconMicOutline /> },
    { name: "IconMicOffOutline", children: <IconMicOffOutline /> },
    { name: "IconMusicOutline", children: <IconMusicOutline /> },
    { name: "IconPaperPlaneOutline", children: <IconPaperPlaneOutline /> },
    { name: "IconSignalOutline", children: <IconSignalOutline /> },
    { name: "IconWifiOutline", children: <IconWifiOutline /> },
    { name: "IconWifiSlashOutline", children: <IconWifiSlashOutline /> },
    { name: "IconAtOutline", children: <IconAtOutline /> },
    { name: "IconBroadcastOutline", children: <IconBroadcastOutline /> },
    { name: "IconEnvelopOutline", children: <IconEnvelopOutline /> },
    { name: "IconInboxOutline", children: <IconInboxOutline /> },
    { name: "IconMovieOutline", children: <IconMovieOutline /> },
    { name: "IconPhoneOutline", children: <IconPhoneOutline /> },
    { name: "IconPhoneCallOutline", children: <IconPhoneCallOutline /> },
    { name: "IconPhoneMissedOutline", children: <IconPhoneMissedOutline /> },
    { name: "IconPhoneOffOutline", children: <IconPhoneOffOutline /> },
    { name: "IconRecordingOutline", children: <IconRecordingOutline /> },
    { name: "IconReplyOutline", children: <IconReplyOutline /> },
    { name: "IconShakeOutline", children: <IconShakeOutline /> },
    { name: "IconVideoOutline", children: <IconVideoOutline /> },
    { name: "IconVideoOffOutline", children: <IconVideoOffOutline /> },
    { name: "IconVolumeHighOutline", children: <IconVolumeHighOutline /> },
    { name: "IconVolumeLowOutline", children: <IconVolumeLowOutline /> },
    { name: "IconVolumeOffOutline", children: <IconVolumeOffOutline /> },
    { name: "IconVolumeSlashOutline", children: <IconVolumeSlashOutline /> },
    { name: "IconCameraOutline", children: <IconCameraOutline /> },
    { name: "IconTVOutline", children: <IconTVOutline /> },
    { name: "IconBatteryBoltOutline", children: <IconBatteryBoltOutline /> },
    { name: "IconBatteryEmptyOutline", children: <IconBatteryEmptyOutline /> },
    { name: "IconDekstopOutline", children: <IconDekstopOutline /> },
    { name: "IconHardDriveOutline", children: <IconHardDriveOutline /> },
    { name: "IconHeadphoneOutline", children: <IconHeadphoneOutline /> },
    { name: "IconPowerOffOutline", children: <IconPowerOffOutline /> },
    { name: "IconPrinterOutline", children: <IconPrinterOutline /> },
    { name: "IconSmartphoneOutline", children: <IconSmartphoneOutline /> },
    { name: "IconSpeakerOutline", children: <IconSpeakerOutline /> },
    { name: "IconShareNodeOutline", children: <IconShareNodeOutline /> },
    { name: "IconBackwardOutline", children: <IconBackwardOutline /> },
    { name: "IconBackwardStepOutline", children: <IconBackwardStepOutline /> },
    { name: "IconPlayCircleOutline", children: <IconPlayCircleOutline /> },
    { name: "IconPauseCircleOutline", children: <IconPauseCircleOutline /> },
    { name: "IconSquareCircleOutline", children: <IconSquareCircleOutline /> },
    { name: "IconForwardOutline", children: <IconForwardOutline /> },
    { name: "IconForwardStepOutline", children: <IconForwardStepOutline /> },
  ],
  fill: [
    { name: "IconBackward", children: <IconBackward /> },
    { name: "IconBackwardStep", children: <IconBackwardStep /> },
    { name: "IconBattery", children: <IconBattery /> },
    { name: "IconBatteryBolt", children: <IconBatteryBolt /> },
    { name: "IconBroadcast", children: <IconBroadcast /> },
    { name: "IconCamera", children: <IconCamera /> },
    { name: "IconEnvelop", children: <IconEnvelop /> },
    { name: "IconForward", children: <IconForward /> },
    { name: "IconForwardStep", children: <IconForwardStep /> },
    { name: "IconHardDrive", children: <IconHardDrive /> },
    { name: "IconHeadphone", children: <IconHeadphone /> },
    { name: "IconInbox", children: <IconInbox /> },
    { name: "IconMessageCircle", children: <IconMessageCircle /> },
    { name: "IconMessageSquare", children: <IconMessageSquare /> },
    { name: "IconMic", children: <IconMic /> },
    { name: "IconMicOff", children: <IconMicOff /> },
    { name: "IconMonitor", children: <IconMonitor /> },
    { name: "IconMovie", children: <IconMovie /> },
    { name: "IconPauseCircle", children: <IconPauseCircle /> },
    { name: "IconPhone", children: <IconPhone /> },
    { name: "IconPhoneCall", children: <IconPhoneCall /> },
    { name: "IconPhoneMissed", children: <IconPhoneMissed /> },
    { name: "IconPhoneOff", children: <IconPhoneOff /> },
    { name: "IconPlayCircle", children: <IconPlayCircle /> },
    { name: "IconPrinter", children: <IconPrinter /> },
    { name: "IconRecording", children: <IconRecording /> },
    { name: "IconReply", children: <IconReply /> },
    { name: "IconShareNode", children: <IconShareNode /> },
    { name: "IconSmartphone", children: <IconSmartphone /> },
    { name: "IconSpeaker", children: <IconSpeaker /> },
    { name: "IconSquareCircle", children: <IconSquareCircle /> },
    { name: "IconTV", children: <IconTV /> },
    { name: "IconVideo", children: <IconVideo /> },
    { name: "IconVideoOff", children: <IconVideoOff /> },
    { name: "IconVolumeHigh", children: <IconVolumeHigh /> },
    { name: "IconVolumeLow", children: <IconVolumeLow /> },
    { name: "IconVolumeOff", children: <IconVolumeOff /> },
    { name: "IconVolumeSlash", children: <IconVolumeSlash /> },
  ],
};
// editing
const editing: IconMapObject = {
  outline: [
    { name: "IconCheckOutline", children: <IconCheckOutline /> },
    { name: "IconXmarkOutline", children: <IconXmarkOutline /> },
    { name: "IconPlusOutline", children: <IconPlusOutline /> },
    { name: "IconMinOutline", children: <IconMinOutline /> },
    { name: "IconCheckDoubleOutline", children: <IconCheckDoubleOutline /> },
    { name: "IconCircleOutline", children: <IconCircleOutline /> },
    { name: "IconCircleDotOutline", children: <IconCircleDotOutline /> },
    { name: "IconCheckCircle2Outline", children: <IconCheckCircle2Outline /> },
    { name: "IconCircleXmarkOutline", children: <IconCircleXmarkOutline /> },
    { name: "IconMinCircleOutline", children: <IconMinCircleOutline /> },
    { name: "IconPlusCircleOutline", children: <IconPlusCircleOutline /> },
    { name: "IconCircleSlashOutline", children: <IconCircleSlashOutline /> },
    { name: "IconCheckCircleOutline", children: <IconCheckCircleOutline /> },
    { name: "IconSquareOutline", children: <IconSquareOutline /> },
    { name: "IconCheckSquare2Outline", children: <IconCheckSquare2Outline /> },
    { name: "IconXmarkSquareOutline", children: <IconXmarkSquareOutline /> },
    { name: "IconPlusSquareOutline", children: <IconPlusSquareOutline /> },
    { name: "IconMinSquareOutline", children: <IconMinSquareOutline /> },
    { name: "IconCheckSquareOutline", children: <IconCheckSquareOutline /> },
    { name: "IconEditOutline", children: <IconEditOutline /> },
    { name: "IconEdit2Outline", children: <IconEdit2Outline /> },
    { name: "IconEdit3Outline", children: <IconEdit3Outline /> },
    { name: "IconScissorsOutline", children: <IconScissorsOutline /> },
    { name: "IconBulbOutline", children: <IconBulbOutline /> },
    { name: "IconEyeOutline", children: <IconEyeOutline /> },
    { name: "IconEyeOffOutline", children: <IconEyeOffOutline /> },
    { name: "IconEyeSlashOutline", children: <IconEyeSlashOutline /> },
    { name: "IconTrashOutline", children: <IconTrashOutline /> },
    { name: "IconTrash2Outline", children: <IconTrash2Outline /> },
    { name: "IconBackspaceOutline", children: <IconBackspaceOutline /> },
    { name: "IconCropOutline", children: <IconCropOutline /> },
    { name: "IconFlipOutline", children: <IconFlipOutline /> },
    { name: "IconLayerGroupOutline", children: <IconLayerGroupOutline /> },
    { name: "IconLayoutOutline", children: <IconLayoutOutline /> },
    { name: "IconLinkOutline", children: <IconLinkOutline /> },
    { name: "IconLink2Outline", children: <IconLink2Outline /> },
    { name: "IconPaintBrushOutline", children: <IconPaintBrushOutline /> },
    { name: "IconPaletteOutline", children: <IconPaletteOutline /> },
    { name: "IconPencilOutline", children: <IconPencilOutline /> },
    { name: "IconSlidersOutline", children: <IconSlidersOutline /> },
    { name: "IconSlidersUpOutline", children: <IconSlidersUpOutline /> },
  ],
  fill: [
    { name: "IconBackspace", children: <IconBackspace /> },
    { name: "IconCheckCircle2", children: <IconCheckCircle2 /> },
    { name: "IconCheckSquare", children: <IconCheckSquare /> },
    { name: "IconCircleDot", children: <IconCircleDot /> },
    { name: "IconCircleXmark", children: <IconCircleXmark /> },
    { name: "IconEdit", children: <IconEdit /> },
    { name: "IconEdit2", children: <IconEdit2 /> },
    { name: "IconEye", children: <IconEye /> },
    { name: "IconEyeSlash", children: <IconEyeSlash /> },
    { name: "IconLayerGroup", children: <IconLayerGroup /> },
    { name: "IconLayout", children: <IconLayout /> },
    { name: "IconMinCircle", children: <IconMinCircle /> },
    { name: "IconMinSquare", children: <IconMinSquare /> },
    { name: "IconPaintBrush", children: <IconPaintBrush /> },
    { name: "IconPalette", children: <IconPalette /> },
    { name: "IconPencil", children: <IconPencil /> },
    { name: "IconPlusCircle", children: <IconPlusCircle /> },
    { name: "IconPlusSquare", children: <IconPlusSquare /> },
    { name: "IconSliders", children: <IconSliders /> },
    { name: "IconSlidersUp", children: <IconSlidersUp /> },
    { name: "IconTrash", children: <IconTrash /> },
    { name: "IconTrash2", children: <IconTrash2 /> },
    { name: "IconXmarkSquare", children: <IconXmarkSquare /> },
  ],
};
// document
const document: IconMapObject = {
  outline: [
    { name: "IconArchiveOutline", children: <IconArchiveOutline /> },
    { name: "IconBookOutline", children: <IconBookOutline /> },
    { name: "IconCalendarOutline", children: <IconCalendarOutline /> },
    { name: "IconFileOutline", children: <IconFileOutline /> },
    { name: "IconFileLinesOutline", children: <IconFileLinesOutline /> },
    { name: "IconFileMinOutline", children: <IconFileMinOutline /> },
    { name: "IconFilePlusOutline", children: <IconFilePlusOutline /> },
    { name: "IconClipboardOutline", children: <IconClipboardOutline /> },
    { name: "IconBookOpenOutline", children: <IconBookOpenOutline /> },
    { name: "IconImageOutline", children: <IconImageOutline /> },
    { name: "IconPantoneOutline", children: <IconPantoneOutline /> },
    { name: "IconListOutline", children: <IconListOutline /> },
    { name: "IconTextOutline", children: <IconTextOutline /> },
    { name: "IconMapsOutline", children: <IconMapsOutline /> },
    { name: "IconFolderOutline", children: <IconFolderOutline /> },
    { name: "IconFolderMinOutline", children: <IconFolderMinOutline /> },
    { name: "IconFolderPlusOutline", children: <IconFolderPlusOutline /> },
  ],
  fill: [
    { name: "IconArchive", children: <IconArchive /> },
    { name: "IconBook", children: <IconBook /> },
    { name: "IconBookOpen", children: <IconBookOpen /> },
    { name: "IconCalendar", children: <IconCalendar /> },
    { name: "IconClipboard", children: <IconClipboard /> },
    { name: "IconFile", children: <IconFile /> },
    { name: "IconFileLines", children: <IconFileLines /> },
    { name: "IconFilePlus", children: <IconFilePlus /> },
    { name: "IconFolder", children: <IconFolder /> },
    { name: "IconFolderMin", children: <IconFolderMin /> },
    { name: "IconFolderPlus", children: <IconFolderPlus /> },
    { name: "IconImage", children: <IconImage /> },
    { name: "IconImage2", children: <IconImage2 /> },
    { name: "IconMaps", children: <IconMaps /> },
    { name: "IconPantone", children: <IconPantone /> },
  ],
};
// medical
const medical: IconMapObject = {
  outline: [
    { name: "IconPulseOutline", children: <IconPulseOutline /> },
    { name: "IconThermometerOutline", children: <IconThermometerOutline /> },
    {
      name: "IconThermometerMinOutline",
      children: <IconThermometerMinOutline />,
    },
    {
      name: "IconThermometerPlusOutline",
      children: <IconThermometerPlusOutline />,
    },
    { name: "IconHeightScaleOutline", children: <IconHeightScaleOutline /> },
    { name: "IconWeightScaleOutline", children: <IconWeightScaleOutline /> },
  ],
  fill: [
    { name: "IconThermometer", children: <IconThermometer /> },
    { name: "IconThermometerMin", children: <IconThermometerMin /> },
    { name: "IconThermometerPlus", children: <IconThermometerPlus /> },
    { name: "IconWeightScale", children: <IconWeightScale /> },
  ],
};
// menu
const menu: IconMapObject = {
  outline: [
    { name: "IconHomeOutline", children: <IconHomeOutline /> },
    { name: "IconMenuOutline", children: <IconMenuOutline /> },
    { name: "IconMenu2Outline", children: <IconMenu2Outline /> },
    { name: "IconMenu3Outline", children: <IconMenu3Outline /> },
    { name: "IconGridOutline", children: <IconGridOutline /> },
    { name: "IconGridRoundOutline", children: <IconGridRoundOutline /> },
    { name: "IconElipsisOutline", children: <IconElipsisOutline /> },
    {
      name: "IconElipsisVerticalOutline",
      children: <IconElipsisVerticalOutline />,
    },
  ],
  fill: [
    { name: "IconGrid", children: <IconGrid /> },
    { name: "IconGridRound", children: <IconGridRound /> },
    { name: "IconHome", children: <IconHome /> },
  ],
};
// person
const person: IconMapObject = {
  outline: [
    { name: "IconPersonOutline", children: <IconPersonOutline /> },
    { name: "IconPersonCheckOutline", children: <IconPersonCheckOutline /> },
    { name: "IconPersonMinOutline", children: <IconPersonMinOutline /> },
    { name: "IconPersonPlusOutline", children: <IconPersonPlusOutline /> },
    { name: "IconPersonXOutline", children: <IconPersonXOutline /> },
    { name: "IconPersonsOutline", children: <IconPersonsOutline /> },
  ],
  fill: [
    { name: "IconPerson", children: <IconPerson /> },
    { name: "IconPersonCheck", children: <IconPersonCheck /> },
    { name: "IconPersonMin", children: <IconPersonMin /> },
    { name: "IconPersonPlus", children: <IconPersonPlus /> },
    { name: "IconPersonX", children: <IconPersonX /> },
    { name: "IconPersons", children: <IconPersons /> },
  ],
};
// security
const security: IconMapObject = {
  outline: [
    { name: "IconLockOutline", children: <IconLockOutline /> },
    { name: "IconUnlockOutline", children: <IconUnlockOutline /> },
    { name: "IconShieldOutline", children: <IconShieldOutline /> },
    { name: "IconShieldSlashOutline", children: <IconShieldSlashOutline /> },
  ],
  fill: [
    { name: "IconLock", children: <IconLock /> },
    { name: "IconUnlock", children: <IconUnlock /> },
    { name: "IconShield", children: <IconShield /> },
    { name: "IconShieldSlash", children: <IconShieldSlash /> },
  ],
};
// shapes
const shapes: IconMapObject = {
  outline: [
    { name: "IconCompassOutline", children: <IconCompassOutline /> },
    { name: "IconAwardOutline", children: <IconAwardOutline /> },

    { name: "IconBoltOutline", children: <IconBoltOutline /> },
    { name: "IconBoltSlashOutline", children: <IconBoltSlashOutline /> },
    { name: "IconClockThreeOutline", children: <IconClockThreeOutline /> },
    { name: "IconDropletOutline", children: <IconDropletOutline /> },
    { name: "IconDropletSlashOutline", children: <IconDropletSlashOutline /> },
    { name: "IconFireOutline", children: <IconFireOutline /> },

    { name: "IconGiftOutline", children: <IconGiftOutline /> },
    { name: "IconLoaderOutline", children: <IconLoaderOutline /> },
    {
      name: "IconMagnifyingGlassOutline",
      children: <IconMagnifyingGlassOutline />,
    },
    {
      name: "IconMagnifyingGlassMinOutline",
      children: <IconMagnifyingGlassMinOutline />,
    },
    {
      name: "IconMagnifyingGlassPlusOutline",
      children: <IconMagnifyingGlassPlusOutline />,
    },
    { name: "IconMoonOutline", children: <IconMoonOutline /> },
    { name: "IconNavigationOutline", children: <IconNavigationOutline /> },
    { name: "IconNavigationUpOutline", children: <IconNavigationUpOutline /> },
    { name: "IconPercentOutline", children: <IconPercentOutline /> },
    { name: "IconPinLocationOutline", children: <IconPinLocationOutline /> },
    { name: "IconLoveOutline", children: <IconLoveOutline /> },
    { name: "IconStarOutline", children: <IconStarOutline /> },
    { name: "IconSunOutline", children: <IconSunOutline /> },
    { name: "IconToogleOffOutline", children: <IconToogleOffOutline /> },
    { name: "IconToogleOnOutline", children: <IconToogleOnOutline /> },
    { name: "IconTruckOutline", children: <IconTruckOutline /> },
    { name: "IconUmbrelaOutline", children: <IconUmbrelaOutline /> },
  ],
  fill: [
    { name: "IconAward", children: <IconAward /> },
    { name: "IconBolt", children: <IconBolt /> },
    { name: "IconBoltSlash", children: <IconBoltSlash /> },
    { name: "IconBulb", children: <IconBulb /> },
    { name: "IconClockThree", children: <IconClockThree /> },
    { name: "IconCompass", children: <IconCompass /> },
    { name: "IconDroplet", children: <IconDroplet /> },
    { name: "IconDropletSlash", children: <IconDropletSlash /> },
    { name: "IconFire", children: <IconFire /> },
    { name: "IconFlag", children: <IconFlag /> },
    { name: "IconGift", children: <IconGift /> },
    { name: "IconLove", children: <IconLove /> },
    { name: "IconMagnifyingGlassMin", children: <IconMagnifyingGlassMin /> },
    { name: "IconMagnifyingGlassPlus", children: <IconMagnifyingGlassPlus /> },
    { name: "IconMoon", children: <IconMoon /> },
    { name: "IconMusic", children: <IconMusic /> },
    { name: "IconNavigation", children: <IconNavigation /> },
    { name: "IconNavigationUp", children: <IconNavigationUp /> },
    { name: "IconPinLocation", children: <IconPinLocation /> },
    { name: "IconStar", children: <IconStar /> },
    { name: "IconSun", children: <IconSun /> },
    { name: "IconToogleOff", children: <IconToogleOff /> },
    { name: "IconToogleOn", children: <IconToogleOn /> },
    { name: "IconTruck", children: <IconTruck /> },
    { name: "IconUmbrela", children: <IconUmbrela /> },
  ],
};
// social
const social: IconMapObject = {
  outline: [
    { name: "IconBehanceOutline", children: <IconBehanceOutline /> },
    { name: "IconFacebookOutline", children: <IconFacebookOutline /> },
    { name: "IconGithubOutline", children: <IconGithubOutline /> },
    { name: "IconGoogleOutline", children: <IconGoogleOutline /> },
    { name: "IconLinkedinOutline", children: <IconLinkedinOutline /> },
    { name: "IconNpmOutline", children: <IconNpmOutline /> },
    { name: "IconTwitterOutline", children: <IconTwitterOutline /> },
  ],
  fill: [
    { name: "IconBehance", children: <IconBehance /> },
    { name: "IconFacebook", children: <IconFacebook /> },
    { name: "IconGithub", children: <IconGithub /> },
    { name: "IconGoogle", children: <IconGoogle /> },
    { name: "IconLinkedin", children: <IconLinkedin /> },
    { name: "IconNpm", children: <IconNpm /> },
    { name: "IconTwitter", children: <IconTwitter /> },
  ],
};

const iconMaps = {
  alert,
  arrow,
  bussiness,
  coding,
  communication,
  editing,
  document,
  medical,
  menu,
  person,
  security,
  shapes,
  social,
};
export default iconMaps;
