export { default as Briefcase } from "./IconBriefcase";
export { default as CreditCard } from "./IconCreditCard";
export { default as Globe2 } from "./IconGlobe2";
export { default as Globe3 } from "./IconGlobe3";
export { default as PieChart } from "./IconPieChart";
export { default as PieChart2 } from "./IconPieChart2";
export { default as PriceTag } from "./IconPriceTag";
export { default as ShoppingBag } from "./IconShoppingBag";
export { default as ShoppingCart } from "./IconShoppingCart";
